# Generated by Django 3.2.6 on 2021-08-24 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Items',
        ),
        migrations.DeleteModel(
            name='ToDoList',
        ),
    ]
